/* Supplied SumAtlas design script, kept as delivered. Only the wrapper (an
   exported init function) and the points marked "SumAtlas:" are changed. */
/* SumAtlas: stampDuty() now comes from the site's SDLT engine (src/gm/engines.ts). */
function paymentFor(loan,rate,years,type){const r=rate/1200,n=years*12;return type==='interest-only'?loan*r:r?loan*r/(1-Math.pow(1+r,-n)):loan/n;}
function mortgage(s){const loan=Math.max(0,s.price-s.deposit),r=s.rate/1200,monthly=paymentFor(loan,s.rate,s.term,s.type);let balance=loan,interest=0,paid=0,yi=0,yc=0,months=0,rows=[];for(let m=1;m<=s.term*12&&balance>.000001;m++){const charge=balance*r,capital=Math.min(balance,Math.max(0,(s.type==='interest-only'?0:monthly-charge)+s.overpay));balance=Math.max(0,balance-capital);interest+=charge;paid+=charge+capital;yi+=charge;yc+=capital;months=m;if(m%12===0||balance<.000001||m===s.term*12){rows.push({year:Math.ceil(m/12),interest:yi,capital:yc,balance,cumulativeInterest:interest});yi=0;yc=0;}}return{loan,monthly,outgoing:loan?Math.min(loan+loan*r,monthly+s.overpay):0,interest,paid,total:paid+balance,balloon:balance,months,rows};}

export function initMortgage(stampDuty){
if(typeof document==='undefined')return;

const $=id=>document.getElementById(id),gbp=(n,d=0)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:d,maximumFractionDigits:d}).format(n),duration=m=>`${Math.floor(m/12)} years${m%12?' '+m%12+' months':''}`;let current,result,baseline;
const defaults={price:350000,deposit:70000,rate:4.75,term:25,type:'repayment',overpay:0,buyer:'standard'};
function read(){return Object.fromEntries(Object.keys(defaults).map(k=>[k,typeof defaults[k]==='number'?Number($(k).value):$(k).value]));}
function valid(s){return Number.isFinite(s.price)&&s.price>=50000&&s.price<=2000000&&Number.isFinite(s.deposit)&&s.deposit>=0&&s.deposit<=s.price&&Number.isFinite(s.rate)&&s.rate>=0&&s.rate<=15&&Number.isInteger(s.term)&&s.term>=1&&s.term<=40&&Number.isFinite(s.overpay)&&s.overpay>=0&&s.overpay<=50000&&['repayment','interest-only'].includes(s.type)&&['standard','first-time','additional'].includes(s.buyer);}
function set(s){for(const k in defaults)$(k).value=s[k];update();}
function line(values,max){return values.map((v,i)=>`${i?'L':'M'}${50+i/(values.length-1)*925},${225-v/max*195}`).join(' ');}
function chart(){const n=current.term;const balances=[result.loan],interests=[0],base=[baseline.loan];for(let y=1;y<=n;y++){const row=result.rows.find(r=>r.year===y),b=baseline.rows.find(r=>r.year===y);balances.push(row?row.balance:result.balloon);interests.push(row?row.cumulativeInterest:result.interest);base.push(b?b.balance:baseline.balloon);}const max=Math.max(result.loan,result.interest,1);let svg='';for(let i=0;i<=4;i++){const y=225-i*195/4;svg+=`<line x1="50" x2="975" y1="${y}" y2="${y}" stroke="#e2e7ef"/><text x="0" y="${y+4}" font-size="12" fill="#626262">£${Math.round(max*i/4/1000)}k</text>`;}svg+=`<path d="${line(base,max)}" fill="none" stroke="#9aa1a9" stroke-width="2" stroke-dasharray="6 5"/><path d="${line(balances,max)}" fill="none" stroke="#2a78d6" stroke-width="3"/><path d="${line(interests,max)}" fill="none" stroke="#eb6834" stroke-width="3"/><text x="50" y="253" font-size="12">Today</text><text x="915" y="253" font-size="12">Year ${n}</text>`;$('balanceChart').innerHTML=svg;$('chartYear').max=n;if(Number($('chartYear').value)>n)$('chartYear').value=n;const y=Number($('chartYear').value);$('yearLabel').textContent=y;$('chartReadout').textContent=`${y?'After year '+y:'Today'}: ${gbp(balances[y])} remaining · ${gbp(result.loan-balances[y])} capital repaid · ${gbp(interests[y])} interest paid.`;}
function update(){const s=read();if(!valid(s)||Object.keys(defaults).some(k=>$(k).value==='')){$('error').textContent='Check your figures: deposit must not exceed the property price, the rate must be 0–15%, and the term must be a whole number from 1–40 years.';$('download').disabled=true;$('share').disabled=true;return false;}$('error').textContent='';$('download').disabled=false;$('share').disabled=false;current=s;document.querySelectorAll('[data-mortgage-type]').forEach(b=>{b.classList.toggle('selected',b.dataset.mortgageType===s.type);b.setAttribute('aria-pressed',String(b.dataset.mortgageType===s.type));});result=mortgage(s);baseline=mortgage({...s,overpay:0});$('deposit').max=s.price;$('depositRange').max=s.price;for(const k of ['price','deposit','rate','term']){const el=$(k+'Range');el.value=s[k];el.style.setProperty('--fill',`${(s[k]-Number(el.min))/(Number(el.max)-Number(el.min))*100}%`);}$('depositPct').textContent=(s.deposit/s.price*100).toFixed(1)+'% of price';const o=result,ltv=o.loan/s.price*100;for(const [id,val] of Object.entries({monthly:gbp(o.outgoing,2),loan:gbp(o.loan),interest:gbp(o.interest),total:gbp(o.total),factLoan:gbp(o.loan),factInterest:gbp(o.interest),factTotal:gbp(o.total),factEnd:s.type==='interest-only'?gbp(o.balloon):duration(o.months),factEndLabel:s.type==='interest-only'?'Still owed at the end':'Mortgage-free in',ltv:ltv.toFixed(1)+'% loan-to-value',payoff:o.balloon>.01?'Balance due at term end':'Paid off in '+duration(o.months),duration:'over '+s.term+' years',monthlyLabel:s.overpay?'Including overpayment':'Monthly repayment'}))$(id).textContent=val;$('summary').textContent=o.loan===0?'Your deposit covers the property price. No mortgage is needed.':`Borrowing ${gbp(o.loan)} at ${s.rate}% with a ${gbp(s.deposit)} deposit.`;document.querySelector('.circle').style.background=`conic-gradient(#2a78d6 0% ${o.total?o.loan/o.total*100:100}%,#eb6834 0% 100%)`;
const allocations=[['Capital repaid',o.loan-o.balloon,'#2a78d6'],['Interest',o.interest,'#eb6834'],...(o.balloon>.01?[['Balance due at the end',o.balloon,'#c3c8ce']]:[])];$('splitbar').innerHTML=allocations.map(([label,value,color])=>`<span style="background:${color};flex:${value}" title="${label}: ${gbp(value)}"></span>`).join('');$('allocation').innerHTML=allocations.map(([label,value,color])=>`<div><span><i style="background:${color}"></i>${label}</span><b>${gbp(value)}</b></div>`).join('');$('perPound').textContent=o.loan?`For every £1 you borrow, you repay £${(o.total/o.loan).toFixed(2)} including any final balance.`:'No borrowing costs.';
const trial=s.overpay?o:mortgage({...s,overpay:100}),saved=baseline.interest-trial.interest,earlier=baseline.months-trial.months;$('savingText').innerHTML=`<p><strong>${gbp(s.overpay||100)} extra a month ${s.overpay?'saves':'could save'} ${gbp(saved)} in interest.</strong></p><p>${earlier>0?'The loan is cleared '+duration(earlier)+' sooner.':s.type==='interest-only'?'Overpayments reduce the balance due at the end.':'Compare a small regular overpayment with your current plan.'}</p>`;const next=[95,90,85,80,75,60].find(x=>x<ltv-.001);$('ltvTip').textContent=next?`${gbp(Math.max(0,s.price*(1-next/100)-s.deposit))} more deposit reaches ${next}% LTV. A lower LTV may unlock other deals; rates depend on the lender.`:'Your deposit is already at or above the 40% band.';
$('rateComparison').innerHTML=[-1,0,1,2,3].map(delta=>({delta,rate:s.rate+delta})).filter(x=>x.rate>=0).map(x=>{const p=paymentFor(o.loan,x.rate,s.term,s.type);return `<div class="rate-row ${x.delta===0?'current':''}"><span>${x.rate.toFixed(2)}% ${x.delta===0?'(yours)':''}</span><strong>${gbp(p,2)}</strong><small>${x.delta?((p-o.monthly>=0?'+':'−')+gbp(Math.abs(p-o.monthly))):'per month'}</small></div>`;}).join('');const tax=stampDuty(s.price,s.buyer);$('upfront').innerHTML=[['Deposit',s.deposit],['Stamp Duty',tax],['Lender, legal & survey fees',2999],['Total cash needed',s.deposit+tax+2999]].map(([label,val])=>`<div><dt>${label}</dt><dd>${gbp(val)}</dd></div>`).join('');$('scheduleBody').innerHTML=o.rows.length?o.rows.map(r=>`<tr><td>${r.year}</td><td>${gbp(r.interest)}</td><td>${gbp(r.capital)}</td><td>${gbp(r.balance)}</td></tr>`).join(''):'<tr><td colspan="4">No mortgage required.</td></tr>';$('balloonNote').textContent=o.balloon>.01?`${gbp(o.balloon)} remains due at the end. This final payment is included in total repayable but excluded from the yearly capital column.`:'Rounded figures; the last year may contain fewer than 12 payments if the mortgage is repaid early.';chart();return true;}
for(const k in defaults)$(k).addEventListener('input',update);for(const k of ['price','deposit','rate','term'])$(k+'Range').addEventListener('input',()=>{$(k).value=$(k+'Range').value;if(k==='price'&&Number($('deposit').value)>Number($('price').value))$('deposit').value=$('price').value;update();});document.querySelectorAll('[data-deposit]').forEach(b=>b.onclick=()=>{$('deposit').value=Number($('price').value)*Number(b.dataset.deposit)/100;update();});document.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>{$('term').value=b.dataset.term;update();});document.querySelectorAll('[data-overpay]').forEach(b=>b.onclick=()=>{$('overpay').value=b.dataset.overpay;update();});document.querySelectorAll('[data-mortgage-type]').forEach(b=>b.onclick=()=>{$('type').value=b.dataset.mortgageType;$('type').dispatchEvent(new Event('change',{bubbles:true}));update();});$('chartYear').oninput=chart;$('mortgageForm').onsubmit=e=>{e.preventDefault();if(update())$('results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};$('reset').onclick=()=>{set(defaults);history.replaceState(null,'',location.pathname);};$('share').onclick=async()=>{if(!update())return;const url=new URL(location.href);url.search=new URLSearchParams(current);url.hash='calculator';try{await navigator.clipboard.writeText(url.href);$('share').textContent='Link copied';}catch{$('share').textContent='Copy this page’s address';history.replaceState(null,'',url);}setTimeout(()=>$('share').textContent='Copy a link to these results',2500);};$('download').onclick=()=>{if(!update())return;const csv='Year,Interest paid,Capital repaid,Balance remaining\n'+result.rows.map(r=>[r.year,r.interest.toFixed(2),r.capital.toFixed(2),r.balance.toFixed(2)].join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='govmath-mortgage-schedule.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};let initial={...defaults};const params=new URLSearchParams(location.search);for(const k in defaults)if(params.has(k))initial[k]=typeof defaults[k]==='number'?Number(params.get(k)):params.get(k);set(valid(initial)?initial:defaults);
if(document.modelContext?.registerTool)try{Promise.resolve(document.modelContext.registerTool({name:'calculate_mortgage',description:'Configure the mortgage calculator and return visible repayment results.',inputSchema:{type:'object',properties:{price:{type:'number'},deposit:{type:'number'},rate:{type:'number'},term:{type:'integer'},type:{type:'string',enum:['repayment','interest-only']},overpay:{type:'number'},buyer:{type:'string',enum:['standard','first-time','additional']}},required:Object.keys(defaults),additionalProperties:false},annotations:{readOnlyHint:false},execute(s){if(!valid(s))throw Error('Invalid mortgage details');set(s);return{monthlyPayment:result.outgoing,totalInterest:result.interest,totalRepayable:result.total,finalBalance:result.balloon};}})).catch(()=>{});}catch{}

}
