/* Supplied SumAtlas design script, kept as delivered. Only the wrapper (an
   exported init function) and the points marked "SumAtlas:" are changed. */
/* SumAtlas: salaryResult() now comes from the site's tested take-home engine
   (src/gm/engines.ts) instead of the inline calculation. */
export function initSalary(salaryResult){
if(typeof document==='undefined')return;

const $=id=>document.getElementById(id),money=(n,d=0)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:d,maximumFractionDigits:d}).format(n),defaults={salary:35000,pension:5,bonus:0,plan:'none',region:'ruk'};let region='ruk',current,result;
function read(){return{salary:Number($('salary').value),pension:Number($('pension').value),bonus:Number($('bonus').value),plan:$('plan').value,region};}
function valid(s){return Number.isFinite(s.salary)&&s.salary>=0&&s.salary<=200000&&Number.isFinite(s.bonus)&&s.bonus>=0&&s.bonus<=1000000&&Number.isFinite(s.pension)&&s.pension>=0&&s.pension<=60&&['none','plan1','plan2','plan4','plan5','pg'].includes(s.plan)&&['ruk','scotland'].includes(s.region);}
function chart(){const cap=200000,points=Array.from({length:81},(_,i)=>({x:i*cap/80,y:salaryResult({...current,salary:i*cap/80,bonus:0}).net}));const path=points.map((p,i)=>`${i?'L':'M'}${60+p.x/cap*910},${235-p.y/cap*205}`).join(' ');let svg='';for(let i=0;i<=4;i++){let y=235-i*205/4;svg+=`<line x1="60" x2="970" y1="${y}" y2="${y}" stroke="#e2e2e2"/><text x="0" y="${y+4}" font-size="12" fill="#666">£${Math.round(cap*i/4000)}k</text>`;}svg+=`<path d="M60,235 L970,30" fill="none" stroke="#eb6834" stroke-width="2" stroke-dasharray="6 4"/><path d="${path}" fill="none" stroke="#2a78d6" stroke-width="3"/><text x="60" y="260" font-size="12">£0 gross salary</text><text x="865" y="260" font-size="12">${money(cap)} gross</text>`;const compare=Number($('compareSalary').value),net=salaryResult({...current,salary:compare,bonus:0}).net;svg+=`<circle cx="${60+Math.min(compare,cap)/cap*910}" cy="${235-net/cap*205}" r="5" fill="#2a78d6"/>`;$('salaryChart').innerHTML=svg;$('salaryChartReadout').textContent=`${money(compare)} annual salary → ${money(net)} take-home per year (${money(net/12,2)} per month). Bonus excluded from this comparison.`;}
function update(){const s=read();if(!valid(s)||['salary','pension','bonus'].some(k=>$(k).value==='')){$('salaryError').textContent='Enter a salary from £0 to £200,000, pension from 0–60%, and bonus from £0 to £1,000,000.';$('salaryDownload').disabled=true;$('salaryShare').disabled=true;return false;}$('salaryError').textContent='';$('salaryDownload').disabled=false;$('salaryShare').disabled=false;current=s;result=salaryResult(s);const o=result;document.querySelectorAll('[data-region]').forEach(b=>{const active=b.dataset.region===region;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});for(const k of ['salary','pension']){const r=$(k+'Range');r.value=s[k];r.style.setProperty('--fill',`${s[k]/Number(r.max)*100}%`);}for(const [id,value] of Object.entries({salaryMonthly:money(o.net/12,2),salaryGross:money(o.gross),salaryNet:money(o.net),salaryDeductions:money(o.gross-o.net),salaryKeep:`You keep ${o.gross?(o.net/o.gross*100).toFixed(1):'0'}%`,salaryRegion:region==='scotland'?'Scotland · 2026/27':'England, Wales & NI · 2026/27'}))$(id).textContent=value;$('salaryDonut').style.background=`conic-gradient(#2a78d6 0% ${o.gross?o.net/o.gross*100:100}%,#eb6834 0% 100%)`;
$('salaryFacts').innerHTML=[['Annual take-home',o.net],['Monthly take-home',o.net/12],['Weekly take-home',o.net/52],['Per working day',o.net/260]].map(([label,n])=>`<div><span>${label}</span><b>${money(n,2)}</b></div>`).join('');const rows=[['Gross pay',o.gross],['Pension contribution',o.pension],['Income Tax',o.tax],['National Insurance',o.ni],['Student loan',o.loan],['Take-home pay',o.net]];$('salaryPayslip').innerHTML=rows.map(([label,n])=>`<tr><td>${label}</td>${[1,12,52].map(d=>`<td>${money(n/d,2)}</td>`).join('')}</tr>`).join('');const parts=[['Take-home pay',o.net,'#2a78d6'],['Income Tax',o.tax,'#eb6834'],['National Insurance',o.ni,'#1baf7a'],['Pension',o.pension,'#4a3aa7'],['Student loan',o.loan,'#9aa1a9']];$('salarySplit').innerHTML=parts.map(([label,n,color])=>`<span style="background:${color};flex:${n}" title="${label}: ${money(n)}"></span>`).join('');$('salaryAllocation').innerHTML=parts.map(([label,n,color])=>`<div><span><i style="background:${color}"></i>${label}</span><b>${money(n)}</b></div>`).join('');$('salaryBands').innerHTML=`<div class="salary-band"><span>Personal Allowance · 0%</span><span>${money(Math.min(o.adjusted,o.allowance))} tax-free</span><strong>£0</strong></div>`+o.bands.map(b=>`<div class="salary-band"><span>${b.name} · ${b.rate*100}%</span><span>${money(b.amount)} taxable</span><strong>${money(b.tax,2)}</strong></div>`).join('');$('salaryRaises').innerHTML=[1000,5000,10000].map(r=>{const extra=salaryResult({...s,salary:s.salary+r}).net-o.net;return`<div class="rate-row"><span>+${money(r)} salary</span><strong>+${money(extra/12,2)}</strong><small>take-home / month</small></div>`;}).join('');const next=salaryResult({...s,salary:s.salary+100}),marginal=(1-((next.net+next.pension-o.pension)-o.net)/100)*100,more=salaryResult({...s,pension:Math.min(60,s.pension+5)});$('salaryInsights').innerHTML=`<div><h3>Your next £100</h3><p>You keep about <strong>${money(next.net-o.net,2)}</strong> in take-home. The marginal tax, NI and loan rate is <strong>${marginal.toFixed(1)}%</strong>, allowing for pension savings.</p></div><div><h3>Increase your pension</h3><p>At ${Math.min(60,s.pension+5)}%, an extra <strong>${money((more.pension-o.pension)/12,2)} a month</strong> goes into your pension, reducing take-home by ${money((o.net-more.net)/12,2)}.</p></div><div><h3>Your Personal Allowance</h3><p>${money(o.allowance)} is available. ${o.adjusted>100000?'Your allowance is reduced by £1 for every £2 of adjusted pay above £100,000.':'Allowance starts reducing when adjusted pay exceeds £100,000.'}</p></div><div><h3>Student loan repayments</h3><p>${s.plan==='none'?'No student loan selected. Choose your plan above to include repayments.':`Your selected plan takes ${money(o.loan/12,2)} a month (${money(o.loan,2)} a year).`}</p></div>`;chart();return true;}
function set(s){region=s.region;for(const k of ['salary','pension','bonus','plan'])$(k).value=s[k];$('plan').dispatchEvent(new Event('change',{bubbles:true}));update();}
for(const k of ['salary','pension','bonus','plan'])$(k).addEventListener('input',update);for(const k of ['salary','pension'])$(k+'Range').addEventListener('input',()=>{$(k).value=$(k+'Range').value;update();});document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{region=b.dataset.region;update();});$('compareSalary').oninput=chart;$('salaryForm').onsubmit=e=>{e.preventDefault();if(update())$('salary-results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};$('salaryReset').onclick=()=>{set(defaults);history.replaceState(null,'',location.pathname);};$('salaryShare').onclick=async()=>{if(!update())return;const url=new URL(location.href);url.search=new URLSearchParams(current);url.hash='calculator';try{await navigator.clipboard.writeText(url.href);$('salaryShare').textContent='Link copied';}catch{history.replaceState(null,'',url);$('salaryShare').textContent='Copy this page’s address';}setTimeout(()=>$('salaryShare').textContent='Copy a link to these results',2500);};$('salaryDownload').onclick=()=>{if(!update())return;const o=result,csv='Item,Annual GBP,Monthly GBP,Weekly GBP\n'+[['Gross pay',o.gross],['Pension',o.pension],['Income Tax',o.tax],['National Insurance',o.ni],['Student loan',o.loan],['Take-home pay',o.net]].map(([label,n])=>[label,n.toFixed(2),(n/12).toFixed(2),(n/52).toFixed(2)].join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='govmath-take-home-pay.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};const p=new URLSearchParams(location.search),initial={...defaults};for(const k in defaults)if(p.has(k))initial[k]=typeof defaults[k]==='number'?Number(p.get(k)):p.get(k);set(valid(initial)?initial:defaults);

}
