"""Build public/gm/govmath-neutral.css: the neutral reading palette.

The design package tints its panels, borders and text pink-purple. Pages
wrapped in `.gm-neutral` swap those tints for neutral greys (as Axis Bank and
the GOV.UK Design System do), keeping wine for buttons, links and selected
states. This script finds every declaration in the calculator stylesheets
that uses a tinted colour and writes a scoped override, so nothing is missed.

Run from the repo root:  python3 scripts/build-neutral-css.py
"""

import re

FILES = [
    "original-layout.css",
    "original-home.css",
    "matching-mortgage.css",
    "matching-salary.css",
    "matching-controls.css",
    "original-brand.css",
    "matching-calculators.css",
    "govmath-site.css",
]

# Tinted colour -> neutral replacement.
MAP = {
    # Panels and soft fills
    "#faf7f9": "#f3f5f8",
    "#f7f9fc": "#f3f5f8",
    "#fcf5f8": "#f3f5f8",
    "#faf3f7": "#eef2f7",
    "#faf0f4": "#eef2f7",
    "#faeef3": "#eef2f7",
    "#faeff4": "#eef2f7",
    "#faf0f6": "#eef2f7",
    "#f9ecf2": "#eef2f7",
    "#efe6ec": "#e6eaef",
    # Borders and dividers
    "#e6d8e1": "#dfe3e8",
    "#eadde5": "#dfe3e8",
    "#e9dfe5": "#dfe3e8",
    "#dfcfd9": "#dfe3e8",
    "#eee7ec": "#e6eaef",
    # Input outlines and other stronger edges
    "#d6c5cf": "#9aa1a9",
    "#c9a4bb": "#9aa1a9",
    "#d6a0b7": "#9aa1a9",
    "#c28a9f": "#9aa1a9",
    "#d8a3ba": "#9aa1a9",
    "#b887a4": "#9aa1a9",
    "#ccc": "#9aa1a9",
    "#b7c9e5": "#9aa1a9",
    # Text
    "#2b2028": "#282828",
    "#645c62": "#5c6066",
}

# Page chrome outside the content wrapper is left alone.
SKIP = re.compile(r"^(:root|html|body|header|footer|\.utility|\.header|\.menu|\.mega|\.ax-mega|\.skip|\.logo|nav\.ax|\.ax-nav|\.topnav)\b")

HEX = re.compile(r"#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b")


def blocks(css: str):
    """Yield (media, selector, body) for every rule, one level of @media deep."""
    i = 0
    n = len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            return
        head = css[i:j].strip()
        if head.startswith("@media"):
            depth, k = 1, j + 1
            while k < n and depth:
                if css[k] == "{":
                    depth += 1
                elif css[k] == "}":
                    depth -= 1
                k += 1
            for _, sel, body in blocks(css[j + 1 : k - 1]):
                yield head, sel, body
            i = k
        elif head.startswith("@"):
            depth, k = 1, j + 1
            while k < n and depth:
                if css[k] == "{":
                    depth += 1
                elif css[k] == "}":
                    depth -= 1
                k += 1
            i = k
        else:
            k = css.find("}", j)
            yield None, head, css[j + 1 : k]
            i = k + 1


def strip_comments(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def main():
    out = [
        "/* Generated by scripts/build-neutral-css.py. Do not edit by hand. */",
        ".gm-neutral {",
        "  --gray: #f3f5f8;",
        "  --ink: #282828;",
        "  --muted: #5c6066;",
        "  --border: #dfe3e8;",
        "  color: #282828;",
        "}",
    ]
    seen = set()
    for f in FILES:
        css = strip_comments(open(f"public/gm/{f}").read())
        for media, sel, body in blocks(css):
            decls = []
            for d in body.split(";"):
                if ":" not in d:
                    continue
                prop, val = d.split(":", 1)
                prop, val = prop.strip(), val.strip()
                if prop.startswith("--"):
                    continue
                new = HEX.sub(lambda m: MAP.get(m.group(0).lower(), m.group(0)), val)
                if new != val:
                    decls.append(f"{prop}:{new}")
            if not decls:
                continue
            sels = [s.strip() for s in sel.split(",") if s.strip() and not SKIP.match(s.strip())]
            if not sels:
                continue
            scoped = ",".join(f".gm-neutral {s}" for s in sels)
            rule = f"{scoped}{{{';'.join(decls)}}}"
            if media:
                rule = f"{media}{{{rule}}}"
            if rule not in seen:
                seen.add(rule)
                out.append(rule)
    open("public/gm/govmath-neutral.css", "w").write("\n".join(out) + "\n")
    print(f"{len(seen)} rules written")


if __name__ == "__main__":
    main()
